name: Deploy
on:
    push:
        branches: master
        paths:
            - 'src/**/*'
            - '**.ts'
            - '**.json'
jobs:
    Deploy:
        runs-on: 'ubuntu-latest'
        steps:
            - name: Deploying...
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSHHOST }}
                  username: ${{ secrets.SSHUSERNAME }}
                  password: ${{ secrets.SSHPASSWORD }}
                  script: |
                      cd /home/themezer/API
                      git reset --hard
                      git pull
                      yarn run deploy
                      pm2 reload /home/themezer/ecosystem.config.js --only API
